export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{
          backgroundColor: "lightblue",
          padding: "1rem",
        }}>
          Welcome Marketing Layout
        </header>
        {children}
        <footer style={{
          backgroundColor: "blue",
          padding: "1rem",
        }}>
          <h1>Marketing Footer</h1>
        </footer>
        </body>
    </html>
  )
}
